version: "3"
services:

  debugger:
    build: debugger/
    stdin_open: true
    tty: true

  nginx:
    build: nginx/
    ports:
      - "8080:80"
    links:
      - target-fpm

  target-fpm:
    build: target-fpm/
    links:
      - debugger
